[package]
name = "earcut-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.16"

[dev-dependencies]
serde_json = { version = "1.0.107", features = ["float_roundtrip"] }
serde = { version = "1.0.188", features = ["derive"] }
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
opt-level = 3
codegen-units = 1
# lto = "fat"
panic = "abort"
